name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SUBMODULE_CHORDSHEETJS_PULL_KEY }}
          submodules: 'recursive'
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn lint
      - run: yarn jest
      - run: yarn build
